import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { selectMealsForDay, findAlternateRecipes } from '../lib/mealPlannerAlgorithm';
import { generateShakeRecipe } from '../lib/shakeGenerator';

export default function useMealPlanner() {
  const [mealPlan, setMealPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Generate a new meal plan for today
  const generateMealPlan = async (date, goals, preferences) => {
    try {
      setLoading(true);
      setError(null);

      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('No user logged in');

      // Use the meal selection algorithm
      const planData = selectMealsForDay(goals, preferences, generateShakeRecipe);

      // Add shake if included and mealFrequency includes snacks
      if (preferences.include_shakes && planData.meals.some(m => m.mealType === 'snack')) {
        const snackMeal = planData.meals.find(m => m.mealType === 'snack');
        if (snackMeal && !snackMeal.recipe.isAutoGenerated) {
          // Replace snack with shake option
          const shake = generateShakeRecipe();
          snackMeal.recipe = shake;
          planData.totalMacros = {
            cal: planData.meals.reduce((sum, m) => sum + (m.recipe.cal || 0), 0),
            protein: planData.meals.reduce((sum, m) => sum + (m.recipe.protein || 0), 0),
            carbs: planData.meals.reduce((sum, m) => sum + (m.recipe.carbs || 0), 0),
            fat: planData.meals.reduce((sum, m) => sum + (m.recipe.fat || 0), 0),
          };
        }
      }

      const dateStr = date instanceof Date ? date.toISOString().split('T')[0] : date;

      // Save to meal_plans table
      const { data: savedPlan, error: saveError } = await supabase
        .from('meal_plans')
        .upsert(
          {
            user_id: user.id,
            plan_date: dateStr,
            meals: planData.meals.map(m => ({
              mealType: m.mealType,
              recipeId: m.recipe.id,
              recipeName: m.recipe.name,
              recipeEmoji: m.recipe.emoji,
              targetMacros: m.targetMacros,
            })),
            total_calories: planData.totalMacros.cal,
            total_protein: planData.totalMacros.protein,
            total_carbs: planData.totalMacros.carbs,
            total_fat: planData.totalMacros.fat,
            accuracy_score: planData.accuracy.overall,
          },
          { onConflict: 'user_id,plan_date' }
        )
        .select()
        .maybeSingle();

      if (saveError) throw saveError;

      // Store full plan in state with recipe objects
      setMealPlan({
        ...planData,
        savedPlanId: savedPlan?.id,
        planDate: dateStr,
      });

      return planData;
    } catch (err) {
      console.error('Error generating meal plan:', err);
      setError(err.message);
      return null;
    } finally {
      setLoading(false);
    }
  };

  // Load meal plan from database for a specific date
  const loadMealPlan = async (date) => {
    try {
      setLoading(true);
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('No user logged in');

      const dateStr = date instanceof Date ? date.toISOString().split('T')[0] : date;

      const { data: plan, error: fetchError } = await supabase
        .from('meal_plans')
        .select('*')
        .eq('user_id', user.id)
        .eq('plan_date', dateStr)
        .maybeSingle();

      if (fetchError) throw fetchError;

      if (plan) {
        setMealPlan({
          savedPlanId: plan.id,
          planDate: plan.plan_date,
          meals: plan.meals,
          totalMacros: {
            cal: plan.total_calories,
            protein: plan.total_protein,
            carbs: plan.total_carbs,
            fat: plan.total_fat,
          },
          accuracy: {
            overall: plan.accuracy_score,
          },
        });
      } else {
        setMealPlan(null);
      }
    } catch (err) {
      console.error('Error loading meal plan:', err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // Swap a recipe in the meal plan
  const swapRecipe = async (mealType, newRecipe, preferences) => {
    if (!mealPlan) return;

    const updatedMeals = mealPlan.meals.map(m => {
      if (m.mealType === mealType) {
        return {
          ...m,
          recipeId: newRecipe.id,
          recipeName: newRecipe.name,
          recipeEmoji: newRecipe.emoji,
        };
      }
      return m;
    });

    // Recalculate totals
    const newTotals = {
      cal: updatedMeals.reduce((sum, m) => {
        const recipe = m.recipeId === newRecipe.id ? newRecipe : mealPlan.meals.find(x => x.recipeId === m.recipeId);
        return sum + (recipe?.cal || 0);
      }, 0),
      protein: 0,
      carbs: 0,
      fat: 0,
    };

    const updatedPlan = {
      ...mealPlan,
      meals: updatedMeals,
      totalMacros: newTotals,
    };

    setMealPlan(updatedPlan);

    // Save to database if plan exists
    if (mealPlan.savedPlanId) {
      try {
        await supabase
          .from('meal_plans')
          .update({ meals: updatedMeals })
          .eq('id', mealPlan.savedPlanId);
      } catch (err) {
        console.error('Error updating meal plan:', err);
      }
    }
  };

  // Get alternative recipes for swapping
  const getAlternatives = (mealType, targetMacros) => {
    return findAlternateRecipes(
      mealType,
      targetMacros,
      { spice_level: 'any', protein_preferences: [] },
      mealPlan?.meals.map(m => m.recipeId) || [],
      5
    );
  };

  // Clear/delete meal plan
  const clearMealPlan = async () => {
    if (!mealPlan?.savedPlanId) return;

    try {
      await supabase
        .from('meal_plans')
        .delete()
        .eq('id', mealPlan.savedPlanId);

      setMealPlan(null);
    } catch (err) {
      console.error('Error clearing meal plan:', err);
    }
  };

  return {
    mealPlan,
    loading,
    error,
    generateMealPlan,
    loadMealPlan,
    swapRecipe,
    getAlternatives,
    clearMealPlan,
  };
}
